//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public int userOneId { get; set; }
        public int userTwoId { get; set; }
        public byte Status { get; set; }
        public int actionUserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
